<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.river</groupId>
        <artifactId>river</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>river-module-stats</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <description>
        stats 模块 - 统计分析
        包括：日报统计、小时统计等
    </description>

    <dependencies>
        <!-- 依赖 system 模块 -->
        <dependency>
            <groupId>com.river</groupId>
            <artifactId>river-module-system</artifactId>
            <version>${revision}</version>
        </dependency>

        <!-- 依赖 affiliate 模块（商家、Offer、分类） -->
        <dependency>
            <groupId>com.river</groupId>
            <artifactId>river-module-affiliate</artifactId>
            <version>${revision}</version>
        </dependency>

        <!-- 依赖 campaign 模块（流量源、成本记录） -->
        <dependency>
            <groupId>com.river</groupId>
            <artifactId>river-module-campaign</artifactId>
            <version>${revision}</version>
        </dependency>

        <!-- 依赖 tracking 模块（点击、转化） -->
        <dependency>
            <groupId>com.river</groupId>
            <artifactId>river-module-tracking</artifactId>
            <version>${revision}</version>
        </dependency>

        <!-- 业务组件 -->
        <dependency>
            <groupId>com.river</groupId>
            <artifactId>river-spring-boot-starter-biz-tenant</artifactId>
        </dependency>

        <!-- Web 相关 -->
        <dependency>
            <groupId>com.river</groupId>
            <artifactId>river-spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.river</groupId>
            <artifactId>river-spring-boot-starter-security</artifactId>
        </dependency>

        <!-- DB 相关 -->
        <dependency>
            <groupId>com.river</groupId>
            <artifactId>river-spring-boot-starter-mybatis</artifactId>
        </dependency>

        <!-- Test 测试相关 -->
        <dependency>
            <groupId>com.river</groupId>
            <artifactId>river-spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
