version: '3.8'
#docker-compose up -d
services:
  postgres:
    image: postgres:17
    container_name: river-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: river
    ports:
      - "5432:5432"
    volumes:
      - /Users/apple/river-docker/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: river-redis
    ports:
      - "6379:6379"
    volumes:
      - /Users/apple/river-docker/redis:/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: river-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - /Users/apple/river-docker/pgadmin:/var/lib/pgadmin
    restart: unless-stopped
