<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.river</groupId>
        <artifactId>river</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>river-module-coupon</artifactId>
    <packaging>pom</packaging>
    <name>${project.artifactId}</name>
    <description>coupon 模块 - 优惠券管理</description>

    <modules>
        <module>river-module-coupon-api</module>
        <module>river-module-coupon-biz</module>
    </modules>
</project>
