<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.river</groupId>
        <artifactId>river-module-tracking</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>river-module-tracking-biz</artifactId>
    <packaging>jar</packaging>
    <name>${project.artifactId}</name>
    <description>tracking 模块业务实现</description>

    <dependencies>
        <dependency>
            <groupId>com.river</groupId>
            <artifactId>river-module-tracking-api</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.river</groupId>
            <artifactId>river-module-affiliate-api</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.river</groupId>
            <artifactId>river-module-system</artifactId>
            <version>${revision}</version>
        </dependency>
        <!-- Spring Boot -->
        <dependency>
            <groupId>com.river</groupId>
            <artifactId>river-spring-boot-starter-biz-tenant</artifactId>
        </dependency>
        <!-- Web -->
        <dependency>
            <groupId>com.river</groupId>
            <artifactId>river-spring-boot-starter-web</artifactId>
        </dependency>
        <!-- Security -->
        <dependency>
            <groupId>com.river</groupId>
            <artifactId>river-spring-boot-starter-security</artifactId>
        </dependency>
        <!-- DB -->
        <dependency>
            <groupId>com.river</groupId>
            <artifactId>river-spring-boot-starter-mybatis</artifactId>
        </dependency>
        <!-- Test -->
        <dependency>
            <groupId>com.river</groupId>
            <artifactId>river-spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
