server:
  port: 48080

--- #################### 数据库相关配置 ####################
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration
      - org.springframework.ai.vectorstore.qdrant.autoconfigure.QdrantVectorStoreAutoConfiguration
      - org.springframework.ai.vectorstore.milvus.autoconfigure.MilvusVectorStoreAutoConfiguration
  # 数据源配置项
  datasource:
    druid:
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        allow:
        url-pattern: /druid/*
        login-username: ${DRUID_USERNAME:admin}
        login-password: ${DRUID_PASSWORD:admin}
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 100
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
    dynamic:
      druid:
        initial-size: 5
        min-idle: 10
        max-active: 50
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 600000
        max-evictable-idle-time-millis: 1800000
        validation-query: SELECT 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
      primary: master
      datasource:
        master:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://postgres:5432/${POSTGRES_DB:river}?prepareThreshold=0
          username: ${POSTGRES_USER:postgres}
          password: ${POSTGRES_PASSWORD}
        slave:
          lazy: true
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://postgres:5432/${POSTGRES_DB:river}?prepareThreshold=0
          username: ${POSTGRES_USER:postgres}
          password: ${POSTGRES_PASSWORD}

  # Redis 配置
  data:
    redis:
      host: redis
      port: 6379

--- #################### 定时任务相关配置 ####################
spring:
  quartz:
    auto-startup: true
    scheduler-name: schedulerName
    job-store-type: jdbc
    wait-for-jobs-to-complete-on-shutdown: true
    properties:
      org:
        quartz:
          scheduler:
            instanceName: schedulerName
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            isClustered: true
            clusterCheckinInterval: 15000
            misfireThreshold: 60000
          threadPool:
            threadCount: 25
            threadPriority: 5
            class: org.quartz.simpl.SimpleThreadPool
    jdbc:
      initialize-schema: NEVER

--- #################### 服务保障相关配置 ####################
lock4j:
  acquire-timeout: 3000
  expire: 30000

--- #################### 监控相关配置 ####################
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info

# 日志文件配置
logging:
  file:
    name: /app/logs/${spring.application.name}.log
  level:
    root: INFO
    com.river: INFO
    org.springframework.context.support.PostProcessorRegistrationDelegate: ERROR

debug: false

--- #################### 芋道相关配置 ####################
river:
  captcha:
    enable: true
  security:
    mock-enable: false
  access-log:
    enable: true
  demo: false
